config/routes.rb
TheBirthdays::Application.routes.draw do

	root :to => 'Home#index', :as => "home"
  get "home" => "Home#index"
# SONGS ROUTES

	get "songs" => "Songs#index", :as => "songs"
	
	get "songs/new" => "Songs#new", :as => "new_song"
	post "songs" => "Songs#create"
	
	get "songs/:id" => "Songs#show", :as => "song"
	
	get "songs/:id/edit" => "Songs#edit", :as => "edit_song"
	put "songs/:id" => "Songs#update", :as => "update_song"
	
	delete "songs/:id" => "Songs#destroy", :as => "destroy_song"
	
# GIGS ROUTES

  get "concerts" => "Gigs#index", :as => "gigs"
    
  get "concerts/new" => "Gigs#new", :as => "new_gig"
  post "concerts" => "Gigs#create"

  get "concerts/:id" => "Gigs#show", :as => "gig"
  
  get "concerts/:id/edit" => "Gigs#edit", :as => "edit_gig"
  put "concerts/:id" => "Gigs#update", :as => "update_gig"
	  
	delete "concerts/:id" => "Gigs#destroy", :as => "destroy_gig"
	
# FANS ROUTES
  get "fans" => "Fans#index", :as => "fans"
  
  get "fans/new" => "Fans#new", :as => "new_fan"
  post "fans" => "Fans#create"
  
  get "fans/:id" => "Fans#show", :as => "fan"
  
  get "fans/:id/edit" => "Fans#edit", :as => "edit_fan"
  put "fans/:id" => "Fans#update", :as => "update_fan"
    
  delete "fans/:id" => "Fans#destroy", :as => "destroy_fan"
  
# ALBUM ROUTES
  get "albums" => "Album#index", :as => "albums"
  
  get "albums/new" => "Album#new", :as => "new_album"
  post "albums" => "Album#create"
  
  get "albums/:id" => "Album#show", :as => "album"
  
  get "albums/:id/edit" => "Album#edit", :as => "edit_album"
  put "albums/:id" => "Album#update", :as => "update_album"
  
  delete "albums/:id" => "Album#destroy", :as => "destroy_album"

end
 

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :date, :title
  validates_presence_of :title
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :body, :title
end

app/models/fans.rb
class Fans < ActiveRecord::Base
  attr_accessible :email, :password, :name
  validates_presence_of :email, :password
end

app/models/gigs.rb
class Gigs < ActiveRecord::Base
  attr_accessible :cost, :date, :venue
  validates_presence_of :date, :venue
end

app/models/songs.rb
class Songs < ActiveRecord::Base
  attr_accessible :title
  validates_presence_of :title  #Q: What is this really doing? 
                                # Is it allowing the flash[:upload_fail] & flash[:update_fail]
                                # notices to work like they're supposed to?
  
end

app/controllers/album_controller.rb
class AlbumController < ApplicationController

  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end
  
  def create
    @album = Album.new
    @album.title = params[:title]
    @album.date = params[:date]
    @album.save
    redirect_to albums_url(@album.id)
  end
  
  def show
    @album = Album.find_by_id(params[:id])
  end
  
  def edit
    @album = Album.find_by_id(params[:id])
  end
  
  def update
    @album = Album.find_by_id(params[:id])
    @album.title = params[:title]
    @album.date = params[:date]
    @album.save
    redirect_to album_url(@album.id)
  end

  def delete
    Album.find_by_id(params[:id]).destroy
    redirect_to albums_url
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fans_controller.rb
class FansController < ApplicationController

  def index
    @fans = Fans.all
  end

  def new
  end
  
  def create
    @fan = Fans.new
    @fan.name = params[:name]
    @fan.email = params[:email]
    @fan.password = params[:password]
    @fan.save
    redirect_to fan_url(@fan.id)
  end
  
  def show
    @fan = Fans.find_by_id(params[:id])
  end
  
  def edit
    @fan = Fans.find_by_id(params[:id])
  end
  
  def update
    @fan = Fans.find_by_id(params[:id])
    @fan.name = params[:name]
    @fan.email = params[:email]
    @fan.password = params[:password]
    @fan.save
    redirect_to fan_url(@fan.id)
  end
  
  def destroy
    Fans.find_by_id(params[:id]).destroy
    redirect_to home_url
  end
  
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController

  def index
    
    @past_gigs = Gigs.where("date < ?", DateTime.now).order('date desc')
    @upcoming_gigs = Gigs.where("date > ?", DateTime.now).order('date asc')
    
    respond_to do |format|
		  format.html
		  format.json { render :json => @gigs }
	  end

    
    # require "date"
    # if DateTime.parse "#{@gig.date}" < DateTime.now
    #   ## put @gig in "past shows"
    # else 
    #   ## put @gig in "upcoming shows"
    # end
  end

  def new
    @gig = Gigs.new
  end

  def create
    @gig = Gigs.new
    @gig.date = params[:date]
    @gig.venue = params[:venue]
    @gig.cost = params[:cost]
    @gig.save
    if @gig.save
      flash[:gig_created] = "Gig at #{@gig.venue} created!"
      redirect_to gigs_url 
    end   
  end
  
  def show
    @gig = Gigs.find_by_id(params[:id])
    # Q: Is it a better practice to seperate out the variables and go:
    #    gig_id = params[:id]
    #    @gig = Gigs.find_by_id(gig_id)
    
    respond_to do |format|
		  format.html
		  format.json { render :json => @gig }
    end
  end

  def edit
    @gig = Gigs.find_by_id(params[:id])
  end
  
  def update
    @gig = Gigs.find_by_id(params[:id])
    @gig.date = params[:date]
    @gig.venue = params[:venue]
    @gig.cost = params[:cost]
    @gig.save
    redirect_to gig_url(@gig.id)
  end
  
  def destroy
    Gigs.find_by_id(params[:id]).delete
    redirect_to gigs_url
    flash[:gig_deleted] = "That gig just got poned."    
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

	def index
		@songs = Songs.all
				
		respond_to do |format|
		  format.html
		  format.json { render :json => @songs }
	  end
	end
	
	def new
	  @song = Songs.new
	end
	
	def create  # Q: How would I rename this to 'upload'
		@song = Songs.new 
		@song.title = params[:title]
		# Q: can we get Songs.create(:title => params[:title]) to work here?
		if @song.save
		  flash[:upload_success] = "#{params[:title]} was uploaded."
		  redirect_to songs_url
		else
		  flash[:upload_fail] = "Please fill in all fields before submitting."
			render 'new'  # Q: how should I think of this 'new' object?
		end	
	end
	
	def show
		@song = Songs.find_by_id(params[:id])
		
		respond_to do |format|
		  format.html
		  format.json { render :json => @lines }
	  end
	end
	
	def edit
		@song = Songs.find_by_id(params[:id])
	end
	
	def update
		@song = Songs.find_by_id(params[:id])
		@song.title = params[:title]
		if @song.update_attributes(params[:songs])  # Q: Why can we access params[:songs] here?
		  flash[:update_success] = "#{params[:title]} was updated."
		  redirect_to songs_url
	  else
	    flash[:update_fail] = "Please fill in all fields before submitting."
	    render 'edit' 
    end	
  end
	
	def destroy
		Songs.find_by_id(params[:id]).destroy
		flash[:destroy_success] = "SONG SUCCESSFULLY DELETED"
		redirect_to songs_url
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/album/edit.html.erb
<h1>Edit Album Here</h1>

<table>
  <%= form_tag(albums_url(@album.id), :method => :put) do %>
  <tr>
    <td><%= label_tag :title, "Title:" %></td>
    <td><%= text_field_tag :title, @album.title %></td>
    <td><%= label_tag :date, "Date:" %></td>
    <td><%= text_field_tag :date, @album.date %></td>
    <td><%= submit_tag "Submit" %></td>
  </tr>
  <% end %>
</table>

<%= link_to "Back to #{@album.title} Page", album_url(@album) %>
<%= link_to "All Albums", albums_url %>

app/views/album/index.html.erb
<h1>Albums</h1>

<p><%= link_to "Create New Album", new_album_url %></p>

<ul>
  <% @albums.each do |album| %>
    <li>
      <%= album.title %> | 
      <%= link_to "Edit", edit_album_url(album.id) %> | 
      <%= link_to "Delete", destroy_album_url(album.id), :method => :delete %>
    </li>
  <% end %>
</ul> 

app/views/album/new.html.erb
<h1>Create New Album Here</h1>

<table>
  <%= form_tag(albums_url, :method => :post) do %>
  <tr>
    <td><%= label_tag :title, "Title:" %></td>
    <td><%= text_field_tag :title %></td> 
    <td><%= label_tag :date, "Date:" %></td>
    <td><%= text_field_tag :date %></td>  
    <td><%= submit_tag "Submit" %></td>
  </tr>
  <% end %>
</table>

app/views/album/show.html.erb
<h1><%= @album.title %></h1>

<p>
  <%= @album.title %>
</p>

<p>
  Released on <%=  @album.date %>
</p>

app/views/fans/edit.html.erb
<table>
  <caption>Edit Your Profile Here</caption>
    <%= form_tag fan_url(@fan.id), :method => :put do %>
    <tr>
      <td>
        <%= label_tag :name, "Name:" %>
        <%= text_field_tag :name, @fan.name %>
      </td>
      <td>
        <%= label_tag :email, "Email address:" %>
        <%= text_field_tag :email, @fan.email %>
      </td>
      <td>
        <%= label_tag :password, "Choose a password:" %>
        <%= text_field_tag :password, @fan.password %>
      </td>
    </tr>
    <tr>
      <td>
        <%= submit_tag "Submit" %>
      </td>
    </tr>
    <% end %>
</table>

<%= link_to "Back to Profile", fan_url(@fan.id) %>

app/views/fans/index.html.erb
<h1>All Fans</h1>

<p><%= link_to "Create Profile", new_fan_url %></p>

<table>
  <caption>ALL FANS</caption>
    <thead>
      <td>NAME</td>
      <td>EMAIL</td>
      <td>PASSWORD</td>
    </thead>
    <% @fans.each do |fan| %>
    <tbody>
      <tr>
        <td><%= fan.name %></td>
        <td><%= fan.email %></td>
        <td><%= fan.password %></td>
        <td><%= link_to "Edit", edit_fan_url(fan.id) %> | </td>
        <td><%= link_to "Delete", destroy_fan_url(fan.id), :method => :delete %></td>
      </tr>
    </tbody>
    <% end %>
</table>

app/views/fans/new.html.erb
<table>
  <caption>Create Your Profile</caption>
    <%= form_tag (fans_url) do %>
    <tr>
      <td>
        <%= label_tag :name, "Name:" %>
        <%= text_field_tag :name %>
      </td>
      <td>
        <%= label_tag :email, "Email address:" %>
        <%= text_field_tag :email %>
      </td>
      <td>
        <%= label_tag :password, "Choose a password:" %>
        <%= text_field_tag :password %>
      </td>
    </tr>
    <tr>
      <td>
        <%= submit_tag "Submit" %>
      </td>
    </tr>
    <% end %>
</table>

app/views/fans/show.html.erb
<h1>Your Profile</h1>

<ul>
  <li><%= @fan.name %></li>
  <li><%= @fan.email %></li>
  <li><%= @fan.password %></li>  
</ul>

<p><%= link_to "Edit", edit_fan_url(@fan.id) %></p>
<p><%= link_to "Delete", destroy_fan_url(@fan.id), :method => :delete %></p>
<p><%= link_to "All Fans", fans_url %></p>

app/views/gigs/edit.html.erb
<h1>This page is for making changes to a particular concert.</h1>

<table>
  <%= form_tag(gig_url(@gig.id), :method => :put) do %>
  <tr>
    <td>
      <%= label_tag :date, "Date: (YEAR-MO-DY-HR:MN)" %>
      <%= text_field_tag :date, @gig.date %>
    </td>
    <td>
      <%= label_tag :venue, "Venue:" %>
      <%= text_field_tag :venue, @gig.venue %>
    </td>
    <td>
      <%= label_tag :cost, "$" %>
      <%= text_field_tag :cost, @gig.cost %>
    </td>
    <td>
      <%= submit_tag "Update Concert" %>
  </tr>
  <% end %>
</table>

<p>
  <%= link_to "Concert Calendar", gigs_url %></p>
</p>

app/views/gigs/index.html.erb
<h1>Concert Calendar</h1>

<table>
  <caption>UPCOMING SHOWS!</caption>
    <tr>
      <th scope="col">DATE</th>
      <th scope="col">VENUE</th>
      <th scope="col">COST</th>
    </tr>
    <% @upcoming_gigs.each do |gig| %>
    <tr>
      <td><%= link_to gig.date.strftime("%A, %B %e, %Y at %l:%M%P"), gig_url(gig.id) %></td> 
      <td><%= gig.venue %></td>
      <td>$<%= gig.cost %></td> 
      <td><%= link_to "Edit", edit_gig_url(gig.id) %> | </td>
      <td><%= link_to "Delete", destroy_gig_url(gig.id), :method => :delete %></td>
      </td>
    </tr>
    <% end %>
</table>

<table>
  <caption>PAST SHOWS...</caption>
    <tr>
      <th scope="col">DATE</th>
      <th scope="col">VENUE</th>
      <th scope="col">COST</th>
    </tr>
    <% @past_gigs.each do |gig| %>
    <tr>
      <td><%= link_to gig.date.strftime("%B %e, %Y"), gig_url(gig.id) %></td> 
      <td><%= gig.venue %></td>
      <td>$<%= gig.cost %></td> 
      <td><%= link_to "Edit", edit_gig_url(gig.id) %> | </td>
      <td><%= link_to "Delete", destroy_gig_url(gig.id), :method => :delete %></td>
      </td>
    </tr>
    <% end %>
</table>

<p><%= link_to "New Concert", new_gig_url %></p>
<p><%= link_to "Songs", songs_url %></p>

app/views/gigs/new.html.erb
<h1>Add a Gig Here</h1>

<table>
  <%= form_tag (gigs_url) do %>
  <tr>
    <td>
      <%= label_tag :date, "Date: (YEAR-MO-DY-HR:MN)" %>
      <%= text_field_tag :date %>
    </td>
    <td>
      <%= label_tag :venue, "Venue:" %>
      <%= text_field_tag :venue %>
    </td>
    <td>
      <%= label_tag :cost, "$" %>
      <%= text_field_tag :cost %>
    </td>
    <td>
      <%= submit_tag "Submit" %>
    </td>
  </tr>
  <% end %>
</table>

<p><%= link_to "Concert Calendar", gigs_url %></p>
<p><%= link_to "Songs List", songs_url %></p>

app/views/gigs/show.html.erb
<table>
  <tr>
    <td><%= @gig.date %></td>
    <td><%= @gig.venue %></td>
    <td>$<%= @gig.cost %></td>
    <td><%= link_to "Edit", edit_gig_url(@gig.id) %>
  </tr>
</table>

<p><%= link_to "Concert Calendar", gigs_url %></p>

app/views/home/index.html.erb
<p>
  <img src=
  "http://a3.ec-images.myspacecdn.com/images01/71/3e43d90101e098fdd4906b1677581c66/l.jpg">
  </img>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheBirthdays</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/edit.html.erb
<h1>edit "<%= @song.title %>" details here</h1>

<%= flash[:update_fail] %>

<%= form_tag(song_url(@song.id), :method => :put) do %>
  <p>
    <%= label_tag :title, "Title:" %> 
    <%= text_field_tag :title, @song.title %>
    <%= submit_tag "Submit" %>
  </p>
<% end %>

<p>
  <%= link_to "#{@song.title} details", song_url(@song.id) %> | 
  <%= link_to "all songs", songs_url %>
</p>

app/views/songs/index.html.erb
<h1>Tunes</h1>
<p>Enjoy streaming these songs by The Birthdays for free!</p>

<%= flash[:upload_success] %>
<%= flash[:update_success] %>
<%= flash[:destroy_success] %>

<table>
  <% @songs.each do |song| %>
  <tr>
    <td><%= link_to song.title, song_url(song.id) %></td>
    <td>PLAY</td> 
    <td><%= link_to "Edit", edit_song_url(song.id) %></td>
    <td><%= link_to "Delete", destroy_song_url(song.id), :method => :delete %></td>
    </td>
  </tr>
  <% end %>
</table>

<p>
  <%= link_to "New", new_song_url %>
</p>

app/views/songs/new.html.erb
<h1>Upload Song Here</h1>

<%= flash[:upload_fail] %>

<table>
  <%= form_tag(songs_url) do %>
  <tr>
    <td><%= label_tag :title, "Title:" %></td>
    <td><%= text_field_tag :title %></td>  
    <td><%= submit_tag "Submit" %></td>
  </tr>
  <% end %>
</table>

<p>
  <%= link_to "All Songs", songs_url %>
</p>

app/views/songs/show.html.erb
<h1>"<%= @song.title %>"</h1>
<%= flash[:notice] %>
<p>
  Play | <%= link_to "Edit", edit_song_url(@song.id) %> | <%= link_to "All Songs", songs_url %>
</p>